import {
  LayoutDashboard,
  Building2,
  Building,
  Home,
  DoorOpen,
  Boxes,
  Layers,
  Warehouse,
  Image as ImageIcon,
  BedDouble,
  Ruler,
  KeyRound,
  FileText,
  FileSignature,
  FilePen,
  FileCheck2,
  ClipboardList,
  ClipboardCheck,
  ClipboardPen,
  Megaphone,
  Globe,
  Share2,
  Rss,
  UserSearch,
  ShieldCheck,
  Shield,
  ShieldAlert,
  CalendarClock,
  CalendarCheck,
  Calendar,
  Repeat,
  RefreshCw,
  LogIn,
  LogOut,
  Users,
  UsersRound,
  UserPlus,
  UserCog,
  UserRound,
  Contact,
  BookUser,
  MessageSquare,
  MessagesSquare,
  MailOpen,
  Send,
  Bell,
  BellRing,
  PhoneCall,
  Inbox,
  Wrench,
  Hammer,
  HardHat,
  Truck,
  PackageOpen,
  Gauge,
  ScanLine,
  Camera,
  Wallet,
  CreditCard,
  Banknote,
  Landmark,
  Receipt,
  ReceiptText,
  Coins,
  CircleDollarSign,
  DollarSign,
  PiggyBank,
  Calculator,
  Scale,
  ArrowLeftRight,
  TrendingUp,
  TrendingDown,
  PieChart,
  BarChart3,
  LineChart,
  FileBarChart,
  FileSpreadsheet,
  Percent,
  Handshake,
  Briefcase,
  Vote,
  Trees,
  Sparkles,
  Bot,
  Workflow,
  ListChecks,
  Clock,
  Plug,
  Webhook,
  Code,
  Settings,
  SlidersHorizontal,
  Palette,
  ScrollText,
  Tags,
  FolderTree,
  FolderOpen,
  Files,
  UploadCloud,
  Smartphone,
  Star,
  ThumbsUp,
} from "lucide-react";

// Sidebar navigation for Geiger Property.
//
// Organized by build priority (P0 → P4), derived from
// docs/COMPETITIVE_FEATURE_ANALYSIS_2026.md. Each top-level area is a priority
// group (see the section dividers below); titles themselves stay clean.
//
// Priority legend:
//   P0 — Universal / table-stakes. Ship at MVP.
//   P1 — Common / expected. Within 90 days.
//   P2 — Uncommon differentiator. Bundled free (where incumbents upsell).
//   P3 — AI moat. Our distinctive value.
//   P4 — Deferred / out of scope (enterprise moats).
//
// Only titles wired into `screens/registry.jsx` render a real screen; the rest
// fall back to ComingSoonScreen while areas are built out one at a time.
export const workspaceNav = [
  // ──────────────────────────────────────────────────────────── P0 (MVP) ──
  // Top-level order follows the manager's daily workflow rather than the
  // build order: overview → people & places → leasing lifecycle → operations
  // → money → documents → reporting → external → settings.
  {
    title: "Overview",
    icon: LayoutDashboard,
  },

  {
    title: "Property",
    icon: Building2,
    subItems: [
      { title: "Properties", icon: Building },
      { title: "Units", icon: DoorOpen },
      { title: "Portfolios", icon: Boxes },
      { title: "Buildings & Blocks", icon: Warehouse },
      { title: "Floor Plans", icon: Ruler },
      { title: "Unit Types", icon: BedDouble },
      { title: "Property Photos & Media", icon: ImageIcon },
      { title: "Amenities", icon: Sparkles },
      { title: "Custom Fields", icon: Tags },
      { title: "Property Groups", icon: Layers },
      { title: "Ownership & Splits", icon: Handshake },
      { title: "Unit Turns & Make-ready", icon: RefreshCw },
      { title: "Keys & Access", icon: KeyRound },
    ],
  },

  {
    title: "Tenants",
    icon: Users,
    subItems: [
      { title: "All Tenants", icon: Users },
      { title: "Tenant Directory", icon: BookUser },
      { title: "Tenant Profiles", icon: UserRound },
      { title: "Household & Occupants", icon: UsersRound },
      { title: "Resident Portal", icon: Smartphone },
      { title: "Documents", icon: Files },
      { title: "Communication Log", icon: MessagesSquare },
      { title: "Announcements", icon: Megaphone },
      { title: "Notices", icon: Bell },
      { title: "Renters Insurance", icon: Shield },
      { title: "Reviews & Feedback", icon: ThumbsUp },
      { title: "Move-out Pipeline", icon: LogOut },
      { title: "Rent Reporting", icon: TrendingUp },
      { title: "Renter Rewards", icon: Star },
    ],
  },

  {
    title: "Leasing",
    icon: FileSignature,
    subItems: [
      { title: "Leases", icon: FileSignature },
      { title: "Lease Builder", icon: FilePen },
      { title: "Lease Templates", icon: Files },
      { title: "State-specific Leases", icon: Scale },
      { title: "E-signature", icon: FileSignature },
      { title: "Addenda & Documents", icon: FileText },
      { title: "Security Deposits", icon: PiggyBank },
      { title: "Move-in", icon: LogIn },
      { title: "Move-out", icon: LogOut },
      { title: "Move-in Inspection", icon: ClipboardCheck },
      { title: "Renewals", icon: Repeat },
      { title: "Rent Increases", icon: TrendingUp },
      { title: "Lease Expirations", icon: CalendarClock },
      { title: "Notices & Violations", icon: ShieldAlert },
      { title: "Deposit Alternatives", icon: Coins },
    ],
  },

  {
    title: "Applications & Screening",
    icon: UserSearch,
    subItems: [
      { title: "Online Applications", icon: FilePen },
      { title: "Application Forms", icon: FileText },
      { title: "Tenant Screening", icon: ShieldCheck },
      { title: "Credit Checks", icon: CreditCard },
      { title: "Background Checks", icon: Shield },
      { title: "Eviction History", icon: ShieldAlert },
      { title: "Income Verification", icon: Banknote },
      { title: "Application Fees", icon: CircleDollarSign },
      { title: "Decisioning", icon: FileCheck2 },
      { title: "Applicant Communication", icon: MessageSquare },
    ],
  },

  {
    title: "Listings & Marketing",
    icon: Megaphone,
    subItems: [
      { title: "Vacancy Listings", icon: Home },
      { title: "Listing Syndication", icon: Share2 },
      { title: "ILS Distribution", icon: Rss },
      { title: "Showings & Tours", icon: CalendarClock },
      { title: "Marketing Website", icon: Globe },
      { title: "Virtual Tours", icon: Camera },
      { title: "Rent Comparables", icon: BarChart3 },
      { title: "Waitlist", icon: Clock },
      { title: "Promotions & Specials", icon: Percent },
      { title: "QR & Yard Signs", icon: ScanLine },
      { title: "Self-guided Showings", icon: KeyRound },
    ],
  },

  {
    title: "Maintenance",
    icon: Wrench,
    subItems: [
      { title: "All Maintenance", icon: Wrench },
      { title: "Work Orders", icon: ClipboardPen },
      { title: "Maintenance Requests", icon: Hammer },
      { title: "Vendors", icon: Truck },
      { title: "Vendor Assignments", icon: HardHat },
      { title: "Photos & Attachments", icon: Camera },
      { title: "Mobile Maintenance", icon: Smartphone },
      { title: "Preventive Maintenance", icon: CalendarCheck },
      { title: "Recurring Work Orders", icon: Repeat },
      { title: "Inspections", icon: ClipboardCheck },
      { title: "Make-ready Boards", icon: RefreshCw },
      { title: "Vendor Portal", icon: Handshake },
      { title: "Estimates & Bids", icon: Calculator },
      { title: "Inventory & Parts", icon: PackageOpen },
      { title: "Meter Readings", icon: Gauge },
      { title: "24/7 Coordination / Contact Center", icon: PhoneCall },
    ],
  },

  {
    title: "Communications",
    icon: MessagesSquare,
    subItems: [
      { title: "Inbox", icon: Inbox },
      { title: "Message Templates", icon: MailOpen },
      { title: "Bulk Messaging", icon: Send },
      { title: "Announcements", icon: Megaphone },
    ],
  },

  {
    title: "Accounting",
    icon: Wallet,
    subItems: [
      { title: "Rent Collection", icon: CircleDollarSign },
      { title: "Online Payments", icon: CreditCard },
      { title: "Autopay", icon: Repeat },
      { title: "Recurring Charges", icon: CalendarClock },
      { title: "Late Fees", icon: Percent },
      { title: "Payment Plans", icon: Coins },
      { title: "Payment Methods", icon: Wallet },
      { title: "Transaction History", icon: ScrollText },
      { title: "Chart of Accounts", icon: FolderTree },
      { title: "Bills & Payables", icon: Receipt },
      { title: "Invoices & Receivables", icon: ReceiptText },
      { title: "Deposits", icon: PiggyBank },
      { title: "Budgeting", icon: Calculator },
    ],
  },

  {
    title: "Owners",
    icon: Briefcase,
    subItems: [
      { title: "Owner Directory", icon: BookUser },
      { title: "Owner Portal", icon: UserCog },
      { title: "Management Fees", icon: Percent },
      { title: "1099 & Tax", icon: ReceiptText },
      { title: "Owner Documents", icon: Files },
    ],
  },

  {
    title: "Documents & eSign",
    icon: Files,
    subItems: [
      { title: "Document Library", icon: FolderOpen },
      { title: "Templates", icon: FileText },
      { title: "E-signature", icon: FileSignature },
      { title: "Shared Files", icon: UploadCloud },
      { title: "Compliance Documents", icon: FileCheck2 },
      { title: "Document Requests", icon: ClipboardList },
    ],
  },

  {
    title: "Reports",
    icon: BarChart3,
    subItems: [
      { title: "Rent Roll", icon: FileSpreadsheet },
      { title: "Delinquency", icon: TrendingDown },
      { title: "Occupancy", icon: PieChart },
      { title: "Owner Statements", icon: FileText },
      { title: "Financial Reports", icon: FileBarChart },
      { title: "Income Statement", icon: LineChart },
      { title: "Balance Sheet", icon: Scale },
      { title: "Cash Flow", icon: TrendingUp },
      { title: "Maintenance Reports", icon: Wrench },
      { title: "Leasing Reports", icon: FileSignature },
      { title: "Custom Report Builder", icon: SlidersHorizontal },
    ],
  },

  {
    title: "Integrations",
    icon: Plug,
    subItems: [
      { title: "Payment Gateways", icon: CreditCard },
      { title: "Ads", icon: Megaphone },
      { title: "Insurance Partners", icon: Shield },
      { title: "Open API", icon: Code },
      { title: "Webhooks", icon: Webhook },
    ],
  },

  {
    title: "Settings",
    icon: Settings,
    subItems: [
      { title: "Company Profile", icon: Building2 },
      { title: "Team & Members", icon: Users },
      { title: "Roles & Permissions", icon: ShieldCheck },
      { title: "Custom Fields", icon: Tags },
      { title: "Tax & Legal", icon: Scale },
      { title: "Branding", icon: Palette },
    ],
  },

  // ─────────────────────────────────────────── Standalone areas & families ──
  {
    title: "Leads & CRM",
    icon: Contact,
    subItems: [
      { title: "Prospects", icon: UserPlus },
      { title: "Pipeline", icon: ListChecks },
      { title: "Follow-ups", icon: BellRing },
      { title: "Lead Sources", icon: Rss },
      { title: "Lead-to-lease", icon: TrendingUp },
    ],
  },

  {
    title: "Banking",
    icon: Landmark,
    subItems: [
      { title: "Landlord Banking", icon: Landmark },
      { title: "Property Sub-accounts", icon: Boxes },
      { title: "High-yield Savings", icon: PiggyBank },
      { title: "Debit & Cards", icon: CreditCard },
      { title: "Payout Accounts", icon: Banknote },
      { title: "Instant / Same-day Payouts", icon: ArrowLeftRight },
      { title: "Flexible Rent", icon: Coins },
      { title: "Cash / Retail Payments", icon: Banknote },
      { title: "1099 E-filing", icon: FileCheck2 },
      { title: "Merchant Accounts", icon: Landmark },
      { title: "Refunds", icon: ArrowLeftRight },
      { title: "Loan Marketplace", icon: DollarSign },
    ],
  },

  {
    title: "Automations",
    icon: Workflow,
  },

  {
    title: "Associations & HOA",
    icon: Building,
    subItems: [
      { title: "Associations", icon: Building2 },
      { title: "Board Members", icon: UsersRound },
      { title: "Dues & Assessments", icon: CircleDollarSign },
      { title: "Violations", icon: ShieldAlert },
      { title: "Common Areas", icon: Trees },
      { title: "Amenity Booking", icon: CalendarCheck },
    ],
  },

  {
    title: "Portals",
    icon: Smartphone,
    subItems: [
      { title: "Owner Portal", icon: Briefcase },
      { title: "Vendor Portal", icon: Truck },
      { title: "Board Portal", icon: UsersRound },
      { title: "Portal Branding", icon: Palette },
    ],
  },

  // ────────────────────────────────────────────────────────── P3 (AI moat) ──
  {
    title: "AI",
    icon: Bot,
    subItems: [
      { title: "Ask-your-data", icon: Bot },
      { title: "AI Insights", icon: Sparkles },
      { title: "Rent Optimization", icon: TrendingUp },
      { title: "Predictive Delinquency", icon: TrendingDown },
      { title: "24/7 Prospect Chat", icon: Bot },
      { title: "AI Listing Writer", icon: Bot },
      { title: "AI Document Parsing", icon: Bot },
      { title: "AI Bookkeeping", icon: Bot },
      { title: "AI Maintenance Triage", icon: Bot },
      { title: "AI Assistant", icon: Sparkles },
    ],
  },

  // ────────────────────────────────────────────────── P4 (Deferred / skip) ──
  {
    title: "HOA — Full Suite",
    icon: Vote,
    subItems: [
      { title: "Architectural Requests", icon: FilePen },
      { title: "Committees", icon: UsersRound },
      { title: "Voting & Elections", icon: Vote },
    ],
  },
];
