import {
  LayoutDashboard,
  Building2,
  Building,
  Home,
  DoorOpen,
  Boxes,
  Layers,
  Image as ImageIcon,
  BedDouble,
  Ruler,
  Warehouse,
  KeyRound,
  FileText,
  FileSignature,
  FilePen,
  FileCheck2,
  ClipboardList,
  ClipboardCheck,
  ClipboardPen,
  Megaphone,
  Globe,
  Share2,
  Rss,
  UserSearch,
  IdCard,
  ShieldCheck,
  Shield,
  ShieldAlert,
  CalendarClock,
  CalendarCheck,
  Calendar,
  Repeat,
  RefreshCw,
  LogIn,
  LogOut,
  Users,
  UsersRound,
  UserPlus,
  UserCog,
  UserCheck,
  UserRound,
  Contact,
  BookUser,
  MessageSquare,
  MessagesSquare,
  Mail,
  MailOpen,
  Send,
  Bell,
  BellRing,
  Phone,
  PhoneCall,
  Inbox,
  Wrench,
  Hammer,
  HardHat,
  Truck,
  PackageOpen,
  Gauge,
  ScanLine,
  Camera,
  Wallet,
  CreditCard,
  Banknote,
  Landmark,
  Receipt,
  ReceiptText,
  Coins,
  CircleDollarSign,
  DollarSign,
  PiggyBank,
  Calculator,
  BookOpen,
  BookOpenCheck,
  Scale,
  ArrowLeftRight,
  TrendingUp,
  TrendingDown,
  PieChart,
  BarChart3,
  LineChart,
  FileBarChart,
  FileSpreadsheet,
  Percent,
  Handshake,
  Briefcase,
  Vote,
  Gavel,
  Trees,
  Sparkles,
  Bot,
  Workflow,
  ListChecks,
  CheckSquare,
  Clock,
  Plug,
  Webhook,
  Code,
  Link2,
  Database,
  Settings,
  SlidersHorizontal,
  Palette,
  Brush,
  Lock,
  Fingerprint,
  ScrollText,
  Languages,
  Tags,
  FolderTree,
  FolderOpen,
  Files,
  UploadCloud,
  Smartphone,
  Star,
  ThumbsUp,
  LifeBuoy,
} from "lucide-react";

// Sidebar navigation for Geiger Property.
//
// Top-level items are the parent feature areas of a modern property-management
// platform; every distinct feature we surveyed across the 2025/26 leaders
// (AppFolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, Rentvine,
// TenantCloud, Rentec, Innago, RentRedi, Avail, Hemlane, TurboTenant, Stessa,
// Baselane) is listed as a sub-item so the full product scope is visible in the
// UI. Feature rarity + our selection rationale are documented in
// docs/competitive-feature-matrix.md and docs/feature-selection.md.
//
// Only titles wired into `screens/registry.jsx` render a real screen; the rest
// fall back to ComingSoonScreen while areas are built out one at a time.
export const workspaceNav = [
  {
    title: "Overview",
    icon: LayoutDashboard,
  },

  {
    // Buildings, units, and unit-level detail. Per-property/unit concerns
    // (photos, amenities, ownership, unit turns…) open as tabs inside the
    // property/unit editor — only workspace-level destinations appear here.
    title: "Properties",
    icon: Building2,
    subItems: [
      { title: "All Properties", icon: Building },
      { title: "Units", icon: DoorOpen },
      { title: "Portfolios", icon: Boxes },
      { title: "Buildings & Blocks", icon: Warehouse },
      { title: "Amenities", icon: Sparkles },
      { title: "Property Photos & Media", icon: ImageIcon },
      { title: "Floor Plans", icon: Ruler },
      { title: "Unit Types", icon: BedDouble },
      { title: "Ownership & Splits", icon: Handshake },
      { title: "Unit Turns & Make-ready", icon: RefreshCw },
      { title: "Keys & Access", icon: KeyRound },
      { title: "Property Groups", icon: Layers },
    ],
  },

  {
    title: "Listings & Marketing",
    icon: Megaphone,
    subItems: [
      { title: "Vacancy Listings", icon: Home },
      { title: "Listing Syndication", icon: Share2 },
      { title: "Marketing Website", icon: Globe },
      { title: "ILS Distribution", icon: Rss },
      { title: "AI Listing Writer", icon: Bot },
      { title: "Virtual Tours", icon: Camera },
      { title: "Rent Comparables", icon: BarChart3 },
      { title: "Showings & Tours", icon: CalendarClock },
      { title: "Self-guided Showings", icon: KeyRound },
      { title: "Waitlist", icon: Clock },
      { title: "Promotions & Specials", icon: Percent },
      { title: "QR & Yard Signs", icon: ScanLine },
    ],
  },

  {
    title: "Leads & CRM",
    icon: Contact,
    subItems: [
      { title: "Prospects", icon: UserPlus },
      { title: "Pipeline", icon: ListChecks },
      { title: "Guest Cards", icon: IdCard },
      { title: "Follow-ups", icon: BellRing },
      { title: "Lead Sources", icon: Rss },
      { title: "Lead-to-lease", icon: TrendingUp },
      { title: "Auto-responders", icon: Bot },
    ],
  },

  {
    title: "Applications & Screening",
    icon: UserSearch,
    subItems: [
      { title: "Online Applications", icon: FilePen },
      { title: "Application Forms", icon: FileText },
      { title: "Tenant Screening", icon: ShieldCheck },
      { title: "Credit Checks", icon: CreditCard },
      { title: "Background Checks", icon: Shield },
      { title: "Eviction History", icon: ShieldAlert },
      { title: "Income Verification", icon: Banknote },
      { title: "Application Fees", icon: CircleDollarSign },
      { title: "Decisioning", icon: FileCheck2 },
      { title: "Applicant Communication", icon: MessageSquare },
    ],
  },

  {
    title: "Leasing",
    icon: FileText,
    subItems: [
      { title: "Leases", icon: FileSignature },
      { title: "Lease Builder", icon: FilePen },
      { title: "Lease Templates", icon: Files },
      { title: "State-specific Leases", icon: Scale },
      { title: "E-signature", icon: FileSignature },
      { title: "Renewals", icon: Repeat },
      { title: "Rent Increases", icon: TrendingUp },
      { title: "Move-in", icon: LogIn },
      { title: "Move-out", icon: LogOut },
      { title: "Move-in Inspection", icon: ClipboardCheck },
      { title: "Notices & Violations", icon: ShieldAlert },
      { title: "Addenda & Documents", icon: FileText },
      { title: "Security Deposits", icon: PiggyBank },
      { title: "Deposit Alternatives", icon: Coins },
      { title: "Lease Expirations", icon: CalendarClock },
    ],
  },

  {
    title: "Tenants",
    icon: Users,
    subItems: [
      { title: "Tenant Directory", icon: Users },
      { title: "Resident Portal", icon: Smartphone },
      { title: "Tenant Profiles", icon: UserRound },
      { title: "Household & Occupants", icon: UsersRound },
      { title: "Communication Log", icon: MessagesSquare },
      { title: "Announcements", icon: Megaphone },
      { title: "Documents", icon: Files },
      { title: "Renters Insurance", icon: Shield },
      { title: "Rent Reporting", icon: TrendingUp },
      { title: "Notices", icon: Bell },
      { title: "Renter Rewards", icon: Star },
      { title: "Reviews & Feedback", icon: ThumbsUp },
      { title: "Move-out Pipeline", icon: LogOut },
    ],
  },

  {
    title: "Owners",
    icon: Briefcase,
    subItems: [
      { title: "Owner Directory", icon: BookUser },
      { title: "Owner Portal", icon: UserCog },
      { title: "Owner Statements", icon: FileSpreadsheet },
      { title: "Owner Distributions", icon: ArrowLeftRight },
      { title: "Owner Contributions", icon: PiggyBank },
      { title: "Ownership Splits", icon: PieChart },
      { title: "Management Fees", icon: Percent },
      { title: "1099 & Tax", icon: ReceiptText },
      { title: "Owner Communication", icon: Mail },
      { title: "Owner Documents", icon: Files },
    ],
  },

  {
    title: "Maintenance",
    icon: Wrench,
    subItems: [
      { title: "Work Orders", icon: ClipboardPen },
      { title: "Maintenance Requests", icon: Hammer },
      { title: "AI Maintenance Triage", icon: Bot },
      { title: "Vendors", icon: Truck },
      { title: "Vendor Assignments", icon: HardHat },
      { title: "Vendor Portal", icon: Handshake },
      { title: "24/7 Coordination", icon: PhoneCall },
      { title: "Preventive Maintenance", icon: CalendarCheck },
      { title: "Recurring Work Orders", icon: Repeat },
      { title: "Inspections", icon: ClipboardCheck },
      { title: "Make-ready Boards", icon: RefreshCw },
      { title: "Inventory & Parts", icon: PackageOpen },
      { title: "Estimates & Bids", icon: Calculator },
      { title: "Mobile Maintenance", icon: Smartphone },
      { title: "Photos & Attachments", icon: Camera },
      { title: "Meter Readings", icon: Gauge },
    ],
  },

  {
    title: "Accounting",
    icon: Wallet,
    subItems: [
      { title: "Rent Collection", icon: CircleDollarSign },
      { title: "Online Payments", icon: CreditCard },
      { title: "Autopay", icon: Repeat },
      { title: "Recurring Charges", icon: CalendarClock },
      { title: "Late Fees", icon: Percent },
      { title: "General Ledger", icon: BookOpen },
      { title: "Chart of Accounts", icon: FolderTree },
      { title: "Bills & Payables", icon: Receipt },
      { title: "Invoices & Receivables", icon: ReceiptText },
      { title: "Bank Accounts", icon: Landmark },
      { title: "Bank Reconciliation", icon: BookOpenCheck },
      { title: "Trust Accounting", icon: Scale },
      { title: "AI Bookkeeping", icon: Bot },
      { title: "Journal Entries", icon: FileText },
      { title: "Deposits", icon: PiggyBank },
      { title: "Payouts & Distributions", icon: ArrowLeftRight },
      { title: "Budgeting", icon: Calculator },
      { title: "1099 E-filing", icon: FileCheck2 },
      { title: "QuickBooks Sync", icon: BookOpenCheck },
      { title: "Utility Billing (RUBS)", icon: Gauge },
      { title: "Payment Plans", icon: Coins },
      { title: "Cash / Retail Payments", icon: Banknote },
    ],
  },

  {
    title: "Banking & Fintech",
    icon: Landmark,
    subItems: [
      { title: "Landlord Banking", icon: Landmark },
      { title: "Property Sub-accounts", icon: Boxes },
      { title: "High-yield Savings", icon: PiggyBank },
      { title: "Debit & Cards", icon: CreditCard },
      { title: "Payment Methods", icon: Wallet },
      { title: "Merchant Accounts", icon: Landmark },
      { title: "Payout Accounts", icon: Banknote },
      { title: "Flexible Rent", icon: Coins },
      { title: "Refunds", icon: ArrowLeftRight },
      { title: "Loan Marketplace", icon: DollarSign },
      { title: "Transaction History", icon: ScrollText },
    ],
  },

  {
    title: "Communications",
    icon: MessagesSquare,
    subItems: [
      { title: "Inbox", icon: Inbox },
      { title: "Email", icon: Mail },
      { title: "Text / SMS", icon: MessageSquare },
      { title: "Bulk Messaging", icon: Send },
      { title: "Announcements", icon: Megaphone },
      { title: "Message Templates", icon: MailOpen },
      { title: "Call Logging", icon: PhoneCall },
      { title: "VoIP & Voicemail", icon: Phone },
      { title: "Notifications", icon: BellRing },
      { title: "Contact Center", icon: Contact },
    ],
  },

  {
    title: "Documents & eSign",
    icon: Files,
    subItems: [
      { title: "Document Library", icon: FolderOpen },
      { title: "Templates", icon: FileText },
      { title: "E-signature", icon: FileSignature },
      { title: "Shared Files", icon: UploadCloud },
      { title: "Compliance Documents", icon: FileCheck2 },
      { title: "Document Requests", icon: ClipboardList },
    ],
  },

  {
    title: "Tasks & Operations",
    icon: ListChecks,
    subItems: [
      { title: "Tasks", icon: CheckSquare },
      { title: "Calendar", icon: Calendar },
      { title: "Reminders", icon: Clock },
      { title: "Automations", icon: Workflow },
      { title: "AI Assistant", icon: Sparkles },
      { title: "Recurring Tasks", icon: Repeat },
      { title: "Team Assignments", icon: UserCheck },
    ],
  },

  {
    title: "Associations & HOA",
    icon: Building,
    subItems: [
      { title: "Associations", icon: Building2 },
      { title: "Board Members", icon: UsersRound },
      { title: "Dues & Assessments", icon: CircleDollarSign },
      { title: "Violations", icon: ShieldAlert },
      { title: "Architectural Requests", icon: FilePen },
      { title: "Committees", icon: UsersRound },
      { title: "Voting & Elections", icon: Vote },
      { title: "Meetings & Minutes", icon: Gavel },
      { title: "Common Areas", icon: Trees },
      { title: "Amenity Booking", icon: CalendarCheck },
    ],
  },

  {
    title: "Reports",
    icon: BarChart3,
    subItems: [
      { title: "Financial Reports", icon: FileBarChart },
      { title: "Rent Roll", icon: FileSpreadsheet },
      { title: "Delinquency", icon: TrendingDown },
      { title: "Occupancy", icon: PieChart },
      { title: "Income Statement", icon: LineChart },
      { title: "Balance Sheet", icon: Scale },
      { title: "Cash Flow", icon: TrendingUp },
      { title: "General Ledger", icon: BookOpen },
      { title: "Owner Statements", icon: FileText },
      { title: "Schedule E / Tax Pack", icon: ReceiptText },
      { title: "Maintenance Reports", icon: Wrench },
      { title: "Leasing Reports", icon: FileSignature },
      { title: "Custom Report Builder", icon: SlidersHorizontal },
      { title: "Scheduled Reports", icon: CalendarClock },
      { title: "Export Center", icon: FileSpreadsheet },
    ],
  },

  {
    title: "Insights",
    icon: TrendingUp,
    subItems: [
      { title: "Portfolio KPIs", icon: Gauge },
      { title: "Occupancy Trends", icon: LineChart },
      { title: "Revenue & NOI", icon: DollarSign },
      { title: "Delinquency Trends", icon: TrendingDown },
      { title: "Lease Expiration Forecast", icon: CalendarClock },
      { title: "Rent Optimization", icon: Sparkles },
      { title: "AI Insights", icon: Bot },
      { title: "Benchmarks", icon: BarChart3 },
    ],
  },

  {
    title: "Portals",
    icon: Smartphone,
    subItems: [
      { title: "Resident Portal", icon: UserRound },
      { title: "Owner Portal", icon: Briefcase },
      { title: "Vendor Portal", icon: Truck },
      { title: "Board Portal", icon: UsersRound },
      { title: "Applicant Portal", icon: UserSearch },
      { title: "Portal Branding", icon: Palette },
      { title: "Mobile App", icon: Smartphone },
    ],
  },

  {
    title: "Integrations",
    icon: Plug,
    subItems: [
      { title: "Accounting Sync", icon: BookOpenCheck },
      { title: "Payment Gateways", icon: CreditCard },
      { title: "Screening Providers", icon: ShieldCheck },
      { title: "Listing Partners", icon: Share2 },
      { title: "Insurance Partners", icon: Shield },
      { title: "Zapier", icon: Workflow },
      { title: "Open API", icon: Code },
      { title: "Webhooks", icon: Webhook },
      { title: "Data Import", icon: Database },
      { title: "Connected Apps", icon: Link2 },
    ],
  },

  {
    title: "Settings",
    icon: Settings,
    subItems: [
      { title: "Company Profile", icon: Building2 },
      { title: "Team & Members", icon: Users },
      { title: "Roles & Permissions", icon: ShieldCheck },
      { title: "Billing & Plans", icon: CreditCard },
      { title: "Branding", icon: Palette },
      { title: "White-label", icon: Brush },
      { title: "Custom Fields", icon: Tags },
      { title: "Notifications", icon: Bell },
      { title: "Security", icon: Lock },
      { title: "SSO", icon: KeyRound },
      { title: "2FA / MFA", icon: Fingerprint },
      { title: "Audit Logs", icon: ScrollText },
      { title: "Tax & Legal", icon: Scale },
      { title: "Localization", icon: Languages },
      { title: "Data & Backup", icon: Database },
      { title: "API & Webhooks", icon: Webhook },
      { title: "Support & SLA", icon: LifeBuoy },
    ],
  },
];
